### ISSUE TITLE
Unable to instantiate sample code of fabcar node.js chaincode on hyperledger AWS blockchain.

### ISSUE THREAD

**Issue by AdB9** [aws-samples/non-profit-blockchain#100]
How to deploy fabcar.js on hyperledger of AWS managed blockchain ?

It gets installed but when trying to instantiate, it throws error.

**Comment by MCLDG** [comment]
This isn't related to non-profit-blockchain. I suggest you take a look at the Managed Blockchain docs: https://docs.aws.amazon.com/managed-blockchain/latest/managementguide/get-started-chaincode.html

**Comment by khacminh** [comment]
@MCLDG 

it seems AWS HLF doesn't support[ fabric-contract-api](https://www.npmjs.com/package/fabric-contract-api). Installing **fabric-contract-api** will cause the error. In this tutorial, the low-level interface **fabric-shim** is used.

For Managed Blockchain, AWS makes it too closed. There is no github repo to show the roadmap and report the issues
