### ISSUE TITLE
Step1: Client node can't be created

### ISSUE THREAD

**Issue by gnorbsl** [aws-samples/non-profit-blockchain#103]
The client node creation fails at BlockchainWorkshopEC2 with the error 
```The image id '[ami-0434d5878c6ad6d4c]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: 431a4359-ad9d-45e7-b45f-95a6981ee1ff)```

Looks like the id is hardcoded into the project, is this a temporary issue or how can I fix this?

**Comment by MCLDG** [comment]
@gnorbsl , can you do a search in the EC2 console for the AMI, and see if it appears under Public images. I see it in my list.

**Comment by gnorbsl** [comment]
Is the image only available to the US region? I tried to create the network
in EU.

MCLDG <notifications@github.com> schrieb am Mo., 10. Aug. 2020, 11:24:

**Comment by MCLDG** [comment]
Yes, that's correct. AMI's are region specific. You could try and copy the AMI to your region, and replace the AMI ID.

**Comment by MCLDG** [comment]
I've added a comment into the README to mention this. I'll merge it at some point. Thanks for pointing this out @gnorbsl
