### ISSUE TITLE
Step 1: Instantiate chaincode gets ACCESS DENIED error

### ISSUE THREAD

**Issue by ajenie7868** [aws-samples/non-profit-blockchain#104]
Run the following command to instantiate the chaincode:
```
docker exec -e "CORE_PEER_TLS_ENABLED=true" -e "CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem" \
   -e "CORE_PEER_ADDRESS=$PEER" -e "CORE_PEER_LOCALMSPID=$MSP" -e CORE_PEER_MSPCONFIGPATH=$MSP_PATH" \
   cli peer chaincode instantiate -o $ORDERER -C $CHANNEL -n $CHAINCODENAME -v $CHAINCODEVERSION \
   -c '{"Args":["init","a","100","b","200"]}' --cafile $CAFILE --tls
```
gets the following error:
```
2020-08-10 14:31:52.975 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2020-08-10 14:31:52.975 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: error endorsing chaincode: rpc error: code = Unknown desc = access denied: channel [mychannel] creator org [m-FYY665VWURBD7EXONWLIKKSPBU]
```

I did peer chaincode list and I can see the chaincode.

I have followed the steps thoroughly. Thanks in advance for your help.

**Comment by MCLDG** [comment]
I've seen this error a few times, and it's always down to missing a step somewhere. I tested the workshop yesterday and all steps worked correctly, so possible you missed a step or had a typo somewhere along the way.

**Comment by ebaizel** [comment]
I would look at the value for `CORE_PEER_MSPCONFIGPATH=$MSP_PATH` and ensure the admin certificates there.  If they are not, you can re-enroll the admin user, described near the end of step 4 https://github.com/aws-samples/non-profit-blockchain/blob/master/ngo-fabric/README.md#step-4---prepare-the-fabric-client-node-and-enroll-an-identity
