### ISSUE TITLE
Error deploying node chaincode

### ISSUE THREAD

**Issue by DJTouchette** [aws-samples/non-profit-blockchain#15]
I realize this sample deploys GO chaincode. I used this as a setup guide to deploy node but after the new release i am getting a npm registry error when trying to deploy chaincode written in node: 

`Error: could not assemble transaction, err Proposal response was not successful, error code 500, msg failed to execute transaction<TRANSACTION_ID>: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/@types%2fgoogle-protobuf failed: cache mode is 'only-if-cached' but no cached response available.`

If anyone knows how to fix this or has any insight !

**Comment by gitesh-tyagi** [comment]
Looks like you are trying to install protobuf dependency on the fly.
Currently installing npm packages in chaincode isn't supported except fabric shim which is available by default.

You can try packaging your dependencies into single node app and deploy that as chaincode.

**Comment by MCLDG** [comment]
As Gitesh said, there's been a change that prevents npm install pulling
from the internet. Check the package.json in the latest master branch .
Yours should look the same. You shouldn't need to install protobuf
separately.  Let me know if you need to install any other packages.
