### ISSUE TITLE
error  accessing frontend(ui) via preview running application

### ISSUE THREAD

**Issue by jetulis** [aws-samples/non-profit-blockchain#16]
I got the seemingly working url https://643d8f2d7c304f8d9a781abd972e43c27.vfs.cloud9.us-east-1.amazonaws.com/
but, it says Oops. No application seems to be running here!

REST-api responds via curl command so Node is running. 
NG is well started but I just can't get to the frontend. how to debug this ?

**Comment by jetulis** [comment]
Indeed. Frontend needs to run on Cloud9, not client. I missed that part.

**Comment by MCLDG** [comment]
Cool, glad you sorted it out.
