### ISSUE TITLE
UI application error

### ISSUE THREAD

**Issue by kenseitogari** [aws-samples/non-profit-blockchain#17]
Part4 : User Interface
step5

I cannot loggin because I don't have a User.
So I try to Sign up, 
but I cannot Sign up 
because any Name and Email already in use.

Why happens this situation and 
do you think where do I make mistakes?

done
RUN REST API
```
[ec2-user@ip-10-0-95-83 ngo-rest-api]$ curl -s -X GET   "http://localhost:3000/donors" -H "content-type: application/json"
[{"donorUserName":"braendle","email":"braendle@def.com","registeredDate":"2018-11-05T14:31:20.182Z","docType":"donor"},{"donorUserName":"edge","email":"edge@def.com","registeredDate":"2018-10-22T11:52:20.182Z","docType":"donor"},{"donorUserName":"edge2","email":"edge2@def.com","registeredDate":"2018-10-22T11:52:20.182Z","docType":"donor"},{"donorUserName":"jane","email":"jane@abc.com","registeredDate":"2018-10-21T09:52:20.182Z","docType":"donor"},{"donorUserName":"louisa","email":"louisa@hij.com","registeredDate":"2018-11-18T05:32:20.182Z","docType":"donor"}]
```

On Cloud9
~/non-profit-blockchain/ngo-ui/src/environments/environment.ts
```
export const environment = {
  production: false,
  host: '',
  port: '',
  dbhost: '',
  dbport: '',
  api_url: 'http://ngo-fabri-Blockcha-1EJ5V39CGSNLJ-153937679.us-east-1.elb.amazonaws.com/',
  test: 'test',
  socket_url: 'ws://ngo-fabri-Blockcha-1EJ5V39CGSNLJ-153937679.us-east-1.elb.amazonaws.com'
};
```

~/non-profit-blockchain/ngo-rest-api/ngo-load-workshop.sh 
```
...
export ENDPOINT=ngo-fabri-Blockcha-1EJ5V39CGSNLJ-153937679.us-east-1.elb.amazonaws.com
export PORT=80
...
```

**Comment by MCLDG** [comment]
Hi, the easiest is to just sign up again with a different user name and
email. User name should be more than 4 characters. If you still have
problems, check to see errors in either the browser console or in the rest
api logs in the ssh session.

**Comment by ebaizel** [comment]
@kenseitogari can you check if your browser url is using `https`, and if it is, can you try switching to `http`and seeing if that resolves it?

**Comment by MCLDG** [comment]
This PR should provide a better indication of what the cause of the error is: #19
