### ISSUE TITLE
How to remove a chaincode on peer?

### ISSUE THREAD

**Issue by VladislavIvanov** [aws-samples/non-profit-blockchain#24]
Hi, @MCLDG ! 

The amazon managed blockchain service and your repo resources are awesome! 
I really appreciate what you have done!

During the chaincode development phase I have installed a lot chaincodes with different versions. I have managed to delete chaincode from the peer file system.

My question is - is there a way to kill the container that corresponds to the chaincode shim for each installed cc?

Thanks!

**Comment by MCLDG** [comment]
Hi Vlad,

Do you mean remove the docker containers from the peer? If so, not in
Amazon managed blockchain, as you have no access to the peer, and there
isn't a cli command to do this. Is this something you would need need?

**Comment by VladislavIvanov** [comment]
Hey, @MCLDG 

Yes, I mean removing the docker containers from the peer. 

How will you advice me to clear all unused chaincodes installed on peer? May be I should  create new peer node and delete the old one? 

Thanks!

**Comment by MCLDG** [comment]
I'm not clear on why you want to clean up the chaincode. Is it causing you
issues?

**Comment by VladislavIvanov** [comment]
During the chaincode development phase I have installed a lot chaincodes with different versions.
Now, I have a final version of my chaincode and I was wondering if I could clean up the redundant versions.

**Comment by MCLDG** [comment]
Ok, in managed blockchain it's not possible. I see this as a nice to have,
unless you see this causing you specific issues.
