### ISSUE TITLE
Endorsement failure during invoke

### ISSUE THREAD

**Issue by arshdeeptinna** [aws-samples/non-profit-blockchain#25]
Thanks for writing this tutorial. It's been very helpful in setting up AWS blockchain.
I am currently running a two org fabric network with one peer in each member. I was able to add the second member to a channel and install and instantiate a chaincode. After add the second org and updating the endorsement policy  the queries work fine but for some reason I can't invoke the chaincode from either org.

I get following error from invoking the ngo chaincode

```
docker exec -e "CORE_PEER_TLS_ENABLED=true" -e "CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem"     -e "CORE_PEER_ADDRESS=$PEER" -e "CORE_PEER_LOCALMSPID=$MSP" -e "CORE_PEER_MSPCONFIGPATH=$MSP_PATH"     cli peer chaincode invoke -C mychannel -n ngo     -c  '{"Args":["createDonor","{\"donorUserName\": \"edge\", \"email\": \"edge@def.com\", \"registeredDate\": \"2018-10-22T11:52:20.182Z\"}"]}' -o $ORDERER --cafile /opt/home/managedblockchain-tls-chain.pem --tls
Error: endorsement failure during invoke. chaincode result: <nil>
```

Can you please help understand what am I doing wrong?

**Comment by MCLDG** [comment]
Did you follow part 5 and update the channel config?

**Comment by arshdeeptinna** [comment]
I did and i did check that the size of the envelope.pb file after it was sign by peer node for client A. Also i am able to query successfully using both the nodes so I am guessing that both the peers nodes have successfully joined the channel.

**Comment by MCLDG** [comment]
I'm guessing your endorsement policy is the same as the repo, i.e. an “or“
policy. If so, i suggest you raise a ticket to the managed blockchain team
and ask them to investigate the issue. Sounds like you've followed the
right steps. The team can check the orderer logs and hopefully gain some
insight.

**Comment by n-bhasin** [comment]
> I did and i did check that the size of the envelope.pb file after it was sign by peer node for client A. Also i am able to query successfully using both the nodes so I am guessing that both the peers nodes have successfully joined the channel.
> 
> Is there anyway to verify the current endorsement policy on a channel?

Hey, did you figure out to solve this error?
