### ISSUE TITLE
Error signing new channel configuration

### ISSUE THREAD

**Issue by SamuelLopesSilva** [aws-samples/non-profit-blockchain#26]
Hello, first of all, great tutorial, it's helping me a lot!

I'm facing a problem when trying to sign the new channel configuration. When I try to run the command in step 10 in part 5 the following error occurs:

```
2019-06-15 23:35:05.173 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: proto: can't skip unknown wire type 6 for common.Envelope
```

**Comment by MCLDG** [comment]
I dont think I've seen that error before. I'd suggest a Google search, but
I dont think it would shed much light on the issue. I suspect you may have
missed a step. Would it be possible to try again, with a new channel for
member a, then add member b.

**Comment by SamuelLopesSilva** [comment]
I restarted everything again and it worked. I really missed some step
