### ISSUE TITLE
Is it possible to call a chaincode written in Go through an node API?

### ISSUE THREAD

**Issue by SamuelLopesSilva** [aws-samples/non-profit-blockchain#27]
Hello, 

I'm trying to use your API code for my chaincode (making the necessary changes), but my chaincode is written in Go. Is this possible?

**Comment by MCLDG** [comment]
Hi, have you tested it to see if it works?

**Comment by SamuelLopesSilva** [comment]
Hello, yes, it worked for a few days but now I'm facing the same problem quoted in another Issue here. Every time I call the path /users it returns the error:

`TypeError: Cannot read property 'curve' of undefined`

**Comment by MCLDG** [comment]
Hmmm, have you recently created a new user or re enrolled the existing
user? Can you check how many keys are in your admin-MSP directory.

**Comment by SamuelLopesSilva** [comment]
I used your answer in another Issue (#31 ) and it worked. Thanks
