### ISSUE TITLE
Error when running aws s3 cp

### ISSUE THREAD

**Issue by torreyj** [aws-samples/non-profit-blockchain#3]
I get this when running: aws s3 cp s3://managedblockchain-beta/service-2.json .

fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

Any ideas?

**Comment by MCLDG** [comment]
I suspect that your iam user does not have headobject permission on s3.
Check if the iam user you are using is admin or at least has sufficient
privileges.
