### ISSUE TITLE
Unable to view console.log() logs printed in ngo.js

### ISSUE THREAD

**Issue by mastermindankur** [aws-samples/non-profit-blockchain#32]
The console.log statements written in ngo.js are not getting printed.

I have tried multiple work arounds but cannot make it to work.  please help, we are stuck.

1) Redirected console.log() output to a file and overridden the console.log function a per the solution suggested here.

```
const util = require('util');
var fs = require('fs');
var log_file = fs.createWriteStream('ankurkhera.log', {flags : 'w'});
var log_stdout = process.stdout;

console.log = function(d) { //
  log_file.write(util.format(d) + '\n');
  log_stdout.write(util.format(d) + '\n');
};

```
2) Tried using the shim.newLogger function and printed the logs but did not work.

```
const shim = require('fabric-shim');
var testLog = shim.newLogger('ankurkhera');
testLog.info('============= START : createSpend ===========')

```
3) Tried looking at logs using docker command but nothing

`docker logs -f cli
`

This is workaround code for my smart contract below
```
'use strict';
const shim = require('fabric-shim');
const util = require('util');

var testLog = shim.newLogger('ankurkhera');
var fs = require('fs');
var log_file = fs.createWriteStream('ankurkhera.log', {flags : 'w'});
var log_stdout = process.stdout;

console.log = function(d) { //
  log_file.write(util.format(d) + '\n');
  log_stdout.write(util.format(d) + '\n');
};

async createSpend(stub, args) {
    console.log('how are you'); //DOES NOT GET SAVED TO FILE
    testLog.info('============= START : createSpend ===========');// NO Logs
    testLog.info('============= END : createSpend ===========');
  }
```

When i call the createSpend() function, the console.log() do not get printed at all.

**Comment by MCLDG** [comment]
The logs appear in the docker container that runs the chaincode on the peer
node. In managed blockchain there is no access to the peer node, and you
unfortunately cannot see the logs.

If you are stuck I suggest two things:

1. Test the chaincode in a local fabric network before deploying to managed
blockchain. Use the first network in fabric samples.
2. Raise a request with the AWS managed blockchain team to get access to
the chaincode logs

**Comment by mastermindankur** [comment]
Thanks Michael, let me try option 2 and get back. 

Since we are beginners not sure how to achieve step 1.

**Comment by swidnikk** [comment]
Hi @MCLDG, seems to me that access to peer node logs is fundamental and would be included in the AWS Managed Blockchain service... I hope it will be added soon.

**Comment by MCLDG** [comment]
Yes, I fully agree.
