### ISSUE TITLE
BAD_REQUEST -- Attempted to include a member which is not in the consortium

### ISSUE THREAD

**Issue by dacarva** [aws-samples/non-profit-blockchain#36]
This is the first time I create a test network and I am having the following issue while creating a channel.

Apparently the docker script is not creating the /opt/home folder and therefore I I always get this error on Part 1 - Step 5:

>     cli peer channel create -c $CHANNEL -f /opt/home/$CHANNEL.pb -o $ORDERER --cafile $CAFILE --tls --timeout 900s
2019-07-16 20:21:55.001 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: BAD_REQUEST -- Attempted to include a member which is not in the consortium

Does anyone have the same issue? 

Thanks

**Comment by MCLDG** [comment]
Hi, I'm guessing you missed a step somewhere. I've seen this a few times
and it's always due to someone missing a step or typing a member id
incorrectly.
