### ISSUE TITLE
How to change the data model?

### ISSUE THREAD

**Issue by Sneez** [aws-samples/non-profit-blockchain#39]
Trying to figure out where the model for donors is defined and how to edit it.  Any tips are appreciated!

**Comment by MCLDG** [comment]
There isn't a model clearly defined. Fabric stores the state in a key value
store, so you can pass in anything you like. Whatever is passed to the rest
api will end up in fabric.

A better approach would be to document the rest api using swagger so that
the model is exposed.

**Comment by Sneez** [comment]
Awesome, I appreciate the quick response.  So if I make changes to the chaincode, I will need to re-deploy the chaincode after every change in order to see the changes working correct?

**Comment by MCLDG** [comment]
Yes @Sneez , correct.
