### ISSUE TITLE
Error while instantiating the ngo chaincode 

### ISSUE THREAD

**Issue by saipraveen23** [aws-samples/non-profit-blockchain#4]
[ec2-user@ip-172-31-92-163 ~]$ docker exec -e "CORE_PEER_TLS_ENABLED=true" -e "CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem"     -e "CORE_PEER_LOCALMSPID=$MSP" -e "CORE_PEER_MSPCONFIGPATH=$MSP_PATH" -e "CORE_PEER_ADDRESS=$PEER"      cli peer chaincode instantiate -o $ORDERER -C mychannel -n ngo -v v0 -c '{"Args":["init"]}' --cafile /opt/home/managedblockchain-tls-chain.pem --tls
2019-02-27 01:48:18.755 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-02-27 01:48:18.755 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: could not assemble transaction, err Proposal response was not successful, error code 500, msg instantiation policy violation: signature set did not satisfy policy

**Comment by saipraveen23** [comment]
@MCLDG 
'mycc' chaincode is working but i am facing this error with 'ngo' chaincode. 
Installation of chaincode is successful.

**Comment by MCLDG** [comment]
Hmmm, that's a tough one to diagnose. Are you sure the env variables are
populated,  such as $PEER? Sounds as though the peer in org1 is not signing
the proposal.

**Comment by bishesh16** [comment]
+1 
@MCLDG I got the exact same error! Any reason why this is failing ?

**Comment by vipulw2011** [comment]
@MCLDG-zz @bishesh16 I am facing same issue and I am following documentation [here](https://github.com/aws-samples/non-profit-blockchain/blob/master/ngo-fabric/README.md).
What I am doing is renaming `chaincode` and `chaincodedir` to fabcar and it's directory as github.com/fabcar/node.

I am stuck since 2 days at this same error. Any help will be appreciated.

**Comment by anweiss** [comment]
Running into this issue all the time when attempting to upgrade to a new chaincode version. According to the Managed Blockchain Service Team via an AWS Support ticket, apparently this is a known issue and the only workaround is to create a new channel.
