### ISSUE TITLE
Policy error on attempting to upgrade chaincode

### ISSUE THREAD

**Issue by Sneez** [aws-samples/non-profit-blockchain#41]
I am getting the following policy error when trying to upgrade changes to my chaincode: 

Error: could not assemble transaction, err Proposal response was not successful, error code 500, msg instantiation policy violation: signature set did not satisfy policy

This was the command I used, and none of the local variables had changed since installation and instantiation of the original chaincode.

docker exec -e "CORE_PEER_TLS_ENABLED=true" -e "CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem"     -e "CORE_PEER_LOCALMSPID=$MSP" -e "CORE_PEER_MSPCONFIGPATH=$MSP_PATH" -e "CORE_PEER_ADDRESS=$PEER"      cli peer chaincode upgrade -o $ORDERER -C mychannel -n ngo -v 2.0 -c '{"Args":[""]}'

**Comment by MCLDG** [comment]
Hi @Sneez , assuming you've followed all the steps in the repo, and now want to upgrade the chaincode version, please raise a ticket with the Managed Blockchain service team. They can investigate the root cause.

**Comment by anweiss** [comment]
FWIW, I'm running into this issue all the time when attempting to upgrade chaincode. I'm using the initial bootstrap admin identity too.
