### ISSUE TITLE
Add another member in API

### ISSUE THREAD

**Issue by SamuelLopesSilva** [aws-samples/non-profit-blockchain#53]
Hello, I am trying to create a network using your example as a guide. I have 4 members (all in my account for testing purposes), I will call them A, B, C, D. I have 2 channels, the first one has A and B and the second one has A, C, and D. I'm kind of confused how to set up these channels and members in the API. How can I do this?

Thank you

**Comment by MCLDG** [comment]
Hi @SamuelLopesSilva , which API are you referring to? In this repo, all channel setup is done using the CLI. The API is only used for invoking/querying chaincode.
