### ISSUE TITLE
Errors when generating configtx channel configuration

### ISSUE THREAD

**Issue by jumping-dragon** [aws-samples/non-profit-blockchain#57]
Hello, I got this issue several times ,when I am about to generate the configtx channel configuration. By executing this command :

> docker exec cli configtxgen -outputCreateChannelTx /opt/home/$CHANNEL.pb -profile OneOrgChannel -channelID $CHANNEL --configPath /opt/home/

![Error Preview](https://user-images.githubusercontent.com/13703305/66195100-7c041200-e6c8-11e9-822b-35e3f2b3d4af.png)

Usually, I would restart everything from zero, and redo it if it happens and hopefully the problem doesn't show up, but :

1. Could anybody tell me what this error means?
2. How would I prevent this problem from happening? 
3. Some references would mean a lot. 👍 I really want to learn what is causing this problem.

Thank you!

**Comment by MCLDG** [comment]
Hi @jumping-dragon , pretty hard to figure out the root cause. I suspect you've missed out  step somewhere, but from the error it's not possible to figure out which one.

**Comment by jumping-dragon** [comment]
Hi @MCLDG ! Really happy to see your response!!!! Currently I have figured out that the problem is on the configtx.yaml that I am using. Due to my laziness of just copying and pasting (SORRY T_T), it turns out that some autoindexting that show up in my pasting caused the configtx.yaml file to be broken. I would love to learn about hyperledger fabric more! Thank you for your awesome tutorial!

**Comment by MCLDG** [comment]
:-) No worries @jumping-dragon , glad you've solved it.
