### ISSUE TITLE
Upgrade usage of Node.js from v8 to a later version

### ISSUE THREAD

**Issue by ebaizel** [aws-samples/non-profit-blockchain#58]
Version 8 is no longer supported as of 12/31/2019 https://nodejs.org/en/about/releases/

We should update wherever we use Node 8 to start using v10 or v12.

**Comment by MCLDG** [comment]
Thanks for the heads up @ebaizel , we will tackle this before years end.

**Comment by MCLDG** [comment]
We've made some progress on this with #74

**Comment by MCLDG** [comment]
PR for this issue coming soon.

**Comment by MCLDG** [comment]
Done. Upgraded to Fabric v1.4, and upgraded Node components to later versions (v14 in most cases)
