### ISSUE TITLE
ExecuteQuery not supported for leveldb

### ISSUE THREAD

**Issue by ryanchuleff** [aws-samples/non-profit-blockchain#69]
I have this deployed up on the starter version of the managed blockchain.  I'm getting this error when I try to run the 'queryAllDocuments' command.  Command is below along with the error response.  Is this something thats just outdated/no longer supported, or is this something that I'm doing wrong?
```
docker exec -e "CORE_PEER_TLS_ENABLED=true" -e "CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem"     -e "CORE_PEER_ADDRESS=$PEER" -e "CORE_PEER_LOCALMSPID=$MSP" -e "CORE_PEER_MSPCONFIGPATH=$MSP_PATH"     cli peer chaincode query -C $CHANNEL -n $CHAINCODENAME -c '{"Args":["queryAllDocuments"]}'
```
```
Error: endorsement failure during query. response: status:500 message:"transaction returned with failure: Error: GET_QUERY_RESULT failed: transaction ID: c74b266961c8d5c2c8e495d117f027fd856fc7e543ed2b9f34ad09508a7a2494: ExecuteQuery not supported for leveldb" 
```

**Comment by MCLDG** [comment]
@ryanchuleff , there is no queryAllDocuments chaincode function - not in the master branch. Where are you seeing this?
