### ISSUE TITLE
How do I deploy my own app?

### ISSUE THREAD

**Issue by aaliashaikh** [aws-samples/non-profit-blockchain#76]
Hi,
I am a student who is working on a blockchain based project. I am using AWS Managed Blockchain for Hyperledger too. I want to know how do I deploy my own app instead of the NGO app?

**Comment by MCLDG** [comment]
You can deploy any application as long as you connect it to the REST API. The REST API abstracts the application from the blockchain.

**Comment by aaliashaikh** [comment]
But in the prerequisite the non-profit-blockchain git repo is cloned. What do I do instead of this?
