### ISSUE TITLE
Creating client node is imposible it repeat the same eror again and again

### ISSUE THREAD

**Issue by Ahadjon** [aws-samples/non-profit-blockchain#77]
~/non-profit-blockchain/ngo-fabric (master) $ ./vpc-client-node.sh
Creating VPC - TODO. Create the VPC, subnets, security group, EC2 client node, VPC endpoint
Create a keypair
Searching for existing keypair named ngo-keypair
Keypair ngo-keypair already exists. Please choose another keypair name by editing this script.

**Comment by MCLDG** [comment]
It means the keypair exists. Check the home directory for a keypair file, and also check the AWS EC2 console, under key pairs. ngo-keypair should be deleted from both before running the script.

**Comment by Ahadjon** [comment]
aws ec2 delete-key-pair --key-name MyKeyPair
