### ISSUE TITLE
Creating new client node stack for new member is impossible

### ISSUE THREAD

**Issue by Ahadjon** [aws-samples/non-profit-blockchain#79]
./vpc-client-node.sh
Creating VPC - TODO. Create the VPC, subnets, security group, EC2 client node, VPC endpoint
Create a keypair

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id None does not exist

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id None does not exist
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --network-id: expected one argument
Searching for existing keypair named -keypair
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: -keypair
Creating a keypair named -keypair. The .pem file will be in your /home/ec2-user directory
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --key-name: expected one argument
Keypair -keypair could not be created

**Comment by MCLDG** [comment]
@Ahadjon , I'm not sure what you are trying to do. What steps have you tried so far, and what instructions are you following?
