### ISSUE TITLE
Post creation blank website fix

### ISSUE THREAD

**Issue by NickMcGrath** [aws-samples/non-profit-blockchain#91]
Hello,
After completing the 5th step my website was just showing blank, it was hard to tell what was wrong. 
after confirming I completed all the steps correctly I found out that there is a bug. you need to add: "import 'core-js/es7/reflect';" to src/polyfills.ts !!
after that, I was able to see and use the website.

**Comment by MCLDG** [comment]
@NickMcGrath , thanks for reporting and debugging this. Which browser / version are you using?

**Comment by NickMcGrath** [comment]
I tried Safari, Chrome, and Firefox. I followed this tutorial to make a project for a class Ill include my project link. You can see the fix under the "Creating the User interface" section. 

https://docs.google.com/document/d/1LgM3aavs1QXX45EsJ9BmPKRTzp6BOf8x_BkmM0CIUIo/edit?usp=sharing

**Comment by MCLDG** [comment]
Thanks @NickMcGrath , I fixed this today, UI should be working again now.
