### ISSUE TITLE
Error when registering user on web UI

### ISSUE THREAD

**Issue by benji-15** [aws-samples/non-profit-blockchain#92]
I've been unable to login or sign up on the web UI. It's giving me an error "Unknown Error. Ensure you are using HTTP, not HTTPS, to access the site." every time. I've tried removing the HTTPS in the url but it's giving me the same error. I know there's an open issue with user registration #60 but this seems to be the opposite of what that issue says.

**Comment by MCLDG** [comment]
@benji-15 , can you check the browser console and see if any error messages are being displayed? This error is usually related to the URL in environment.ts being incorrect.

**Comment by benji-15** [comment]
I got it to work after deleting https:// in the url, thanks.
